version: "3.1"
services:
  db:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: dbname
      MYSQL_USER: root
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - ./conf:/etc/mysql/conf.d
      - persistent:/var/lib/mysql
    networks:
      - default

  www:
    image: php:7.4-apache  # Utilizamos la imagen oficial de PHP con Apache
    container_name: lamp-container
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
      - ./conf/apache:/etc/apache2/sites-available  # Volumen para archivos de configuración de Apache
    environment:
      - MYSQL_HOST=db  # Conexión al contenedor de MySQL
      - MYSQL_DATABASE=dbname
      - MYSQL_USER=root
      - MYSQL_PASSWORD=test
    depends_on:
      - db  # Asegura que db esté levantado antes de iniciar www
    networks:
      - default
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    ports:
      - "8000:80"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
      MYSQL_HOST: db
    depends_on:
      - db
    networks:
      - default
    restart: always

volumes:
  persistent:

networks:
  default:
    driver: bridge
